name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: kupuma-ru21/auto-release-actions/blob/main/.github/workflows/called.yml@main
    with:
      config-path: .github/labeler.yml
    secrets:
      envPAT: ${{ secrets.envPAT }}
