name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-release-note:
    uses: kupuma-ru21/auto-release-actions/.github/workflows/reusable-workflow.yml@v1
    secrets: inherit
