name: Create release tag and release note.

on:
  workflow_call:
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: kupuma-ru21/auto-release-note/blob/main/.github/workflows/release-note.yml@main
