name: release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-workflow-passing-data:
    uses: kupuma-ru21/auto-release-note-actions/.github/workflows/reusable-workflow.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
